services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\TopicActivityBundle\Controller\:
    resource: '../../Controller/'
  Tourze\TopicActivityBundle\Repository\:
    resource: '../../Repository/'
  Tourze\TopicActivityBundle\Service\:
    resource: '../../Service/'
    public: true
  Tourze\TopicActivityBundle\EventListener\:
    resource: '../../EventListener/'
    public: true

